import { promises as fs } from "fs";
import { join } from "path";

import { eq } from "drizzle-orm";
import type { AdvancedOptions } from "@promptalicious/shared-infra";

import { db } from "@/db/connection";
import { tools } from "@/db/schema/tools.schema";
import { projectConfiguration } from "@/db/schema/project.schema";
import { executionStateCacheService } from "@/services/execution-state-cache.service";

export interface ExportInstructionsRequest {
  includeDisabledTools: boolean;
}

export interface ExportInstructionsResponse {
  markdown: string;
  generatedAt: Date;
  toolsIncluded: number;
  advancedOptions: Record<string, unknown>;
}

export async function generateExportInstructions(
  request: ExportInstructionsRequest,
): Promise<ExportInstructionsResponse> {
  const projectConfig = await db
    .select()
    .from(projectConfiguration)
    .where(eq(projectConfiguration.id, 1))
    .limit(1);

  if (projectConfig.length === 0) {
    throw new Error("No project configured");
  }

  const toolsFilter = request.includeDisabledTools
    ? []
    : [eq(tools.enabled, true)];

  const discoveredTools = await db
    .select()
    .from(tools)
    .where(toolsFilter.length > 0 ? toolsFilter[0] : undefined);

  if (discoveredTools.length === 0) {
    throw new Error("No tools configured");
  }

  const toolsToExport = request.includeDisabledTools
    ? discoveredTools
    : discoveredTools.filter((tool) => tool.enabled);

  const generatedAt = new Date();
  const advancedOptions = buildAdvancedOptionsObject();

  const markdown = await generateMarkdownTemplate({
    projectConfig: projectConfig[0]!,
    tools: toolsToExport,
    generatedAt,
    advancedOptions,
  });

  return {
    markdown,
    generatedAt,
    toolsIncluded: toolsToExport.length,
    advancedOptions,
  };
}

interface MarkdownTemplateParams {
  projectConfig: {
    name: string;
    targetProjectPath: string;
    workspacePath: string;
  };
  tools: Array<{
    id: string;
    name: string;
    description: string;
    sourceDescription: string | null;
    sourceFilePath: string;
    workspaceDir: string;
    parametersSchema: unknown;
    enabled: boolean;
  }>;
  generatedAt: Date;
  advancedOptions: Record<string, unknown>;
}

async function generateMarkdownTemplate(
  params: MarkdownTemplateParams,
): Promise<string> {
  const { projectConfig, tools, generatedAt, advancedOptions } = params;

  let markdown = `# Export Instructions

Generated: ${generatedAt.toISOString()}
Feature: ${projectConfig.name}

## Changes Summary

- ${tools.length} tools configured
- ${tools.filter((t) => t.enabled).length} tools enabled
- AI SDK options ${Object.keys(advancedOptions).length > 0 ? "customised" : "using defaults"}

`;

  markdown += `## Step 1: Update Tool Definitions

For each tool, apply these changes:

`;

  for (const tool of tools) {
    const toolExecuteFunction = await readToolExecuteFunction(
      tool.workspaceDir,
    );

    markdown += `### Tool: ${tool.name}

**File**: ${tool.sourceFilePath}
**Function**: ${tool.name}

**Updated execute function**:

\`\`\`typescript
${toolExecuteFunction}
\`\`\`

**Updated description**:

\`\`\`
${tool.description}
\`\`\`

`;
  }

  markdown += `## Step 2: Update AI SDK Call

**Current file**: ${projectConfig.targetProjectPath}

Replace your generateText call with:

\`\`\`typescript
const result = await generateText({
  model: openai('gpt-4o-mini'),
  prompt: yourPrompt,
  tools: {
`;

  for (const tool of tools) {
    const toolExecuteFunction = await readToolExecuteFunction(
      tool.workspaceDir,
    );

    markdown += `    ${tool.name}: tool({
      description: '${tool.description.replace(/'/g, "\\'")}',
      parameters: ${JSON.stringify(tool.parametersSchema, null, 2).split("\n").join("\n      ")},
      execute: ${toolExecuteFunction}
    }),
`;
  }

  markdown += `  },
`;

  if (Object.keys(advancedOptions).length > 0) {
    for (const [key, value] of Object.entries(advancedOptions)) {
      markdown += `  ${key}: ${JSON.stringify(value)},\n`;
    }
  }

  markdown += `})
\`\`\`

## Step 3: Refactoring Checklist

- [ ] Copy updated execute functions to original tool files
- [ ] Update tool descriptions in tool definitions
- [ ] Update AI SDK call with new options
- [ ] Test execution with updated configuration
- [ ] Remove promptalicious workspace directory if no longer needed

---

**Generated by promptalicious** - LLM debugging and iteration tool
`;

  return markdown;
}

async function readToolExecuteFunction(workspaceDir: string): Promise<string> {
  try {
    const toolFilePath = join(process.cwd(), workspaceDir, "tool.ts");
    const toolFileContent = await fs.readFile(toolFilePath, "utf-8");

    const lines = toolFileContent.split("\n");
    const nonImportLines = lines.filter(
      (line) => !line.trim().startsWith("import "),
    );
    const functionCode = nonImportLines.join("\n").trim();

    return functionCode || toolFileContent;
  } catch {
    return (
      "// Unable to read execute function from workspace\n// Path: " +
      workspaceDir
    );
  }
}

function buildAdvancedOptionsObject(): Record<string, unknown> {
  const currentExecution = executionStateCacheService.getCurrentExecution();

  if (currentExecution?.advancedOptions) {
    return currentExecution.advancedOptions as Record<string, unknown>;
  }

  const defaultOptions: AdvancedOptions = {
    toolChoice: "auto",
    maxToolRoundtrips: 10,
  };

  return defaultOptions as Record<string, unknown>;
}
